# Chapter 5 Classifiers

# Import Training&Test Data after Data Preprocessing

All csv files imported here shall be shuffled, thus shall be the same with shuffled one displayed in Data Preprocessing (in datasplit_train_test.ipynb file). Data shall be the same version with backup stored in file chp5_classifiers.

In [376]:
import pandas as pd
import numpy as np

In [377]:
# Read in csv file of training and testing record
train_df = pd.read_csv("./chp5_classifiers/version_X/train_set.csv")
test_df = pd.read_csv("./chp5_classifiers/version_X/test_set.csv") 

test_wtpopl = pd.read_csv("./chp5_classifiers/version_X/test_wtpopl.csv") 

In [378]:
# Display first 5 rows of training dataframe, check whether the same with shuffled one displayed in Data Preprocessing file
train_df.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     741       440       15        168        6         0   
1         0      23        80        0         31       13         3   
2         0     313       437        3         18        0         0   
3        32    1839      2109        5       1157        9         0   
4         0     191       180        0         15        0         0   

   crew_num  popularity  
0         2         1.0  
1         3         1.0  
2         1         1.0  
3         0         0.0  
4         2         1.0

In [379]:
# Extract label class popularity from training set
labl_df = train_df['popularity']
labl_df.head()

0    1.0
1    1.0
2    1.0
3    0.0
4    1.0
Name: popularity, dtype: float64

In [380]:
# Remove label class from training set
train_set = train_df.drop(columns=['popularity'])
train_set.head()

language  cast_0  director  genre_0  company_0  country  cast_num  crew_num
0         0     741       440       15        168        6         0         2
1         0      23        80        0         31       13         3         3
2         0     313       437        3         18        0         0         1
3        32    1839      2109        5       1157        9         0         0
4         0     191       180        0         15        0         0         2

In [381]:
# Display first 5 rows of test dataframe, check whether the same with shuffled one displayed before
test_df.head()

language  cast_0  director  genre_0  company_0  country  cast_num  crew_num
0         0     155       967        5        433       43         0         0
1         0     342       869        5         13        0         1         3
2         0     469      1515        0        762       18         0         0
3         0      79       341        0        100        0         0         1
4         0    1784      1468        0        416        6         0         3

In [382]:
# Transfer type of ddtaframe to numpy array for training and test sets and label set
train_ary = np.array(train_set)
print(train_ary[0:5])
test_ary = np.array(test_df)
print(test_ary[0:5])
labl_ary = np.array(labl_df)
print(labl_ary[0:5])

[[   0  741  440   15  168    6    0    2]
 [   0   23   80    0   31   13    3    3]
 [   0  313  437    3   18    0    0    1]
 [  32 1839 2109    5 1157    9    0    0]
 [   0  191  180    0   15    0    0    2]]
[[   0  155  967    5  433   43    0    0]
 [   0  342  869    5   13    0    1    3]
 [   0  469 1515    0  762   18    0    0]
 [   0   79  341    0  100    0    0    1]
 [   0 1784 1468    0  416    6    0    3]]
[1. 1. 1. 0. 1.]


# Classification

So far, all data array required shall be organized in suitable format and correctly imported.

Training Features: train_ary

Training Labels: labl_ary

Testing Features: test_ary

In [383]:
from sklearn.neighbors import KNeighborsClassifier

In [384]:
from sklearn.naive_bayes import GaussianNB

In [385]:
from sklearn.svm import SVC

In [386]:
from sklearn.neural_network import MLPClassifier

In [387]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [388]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [389]:
# Array of movies consists of features selected as input
X = train_ary

In [390]:
# Popularity label of sample data 0-unpopular 1-popular
y = labl_ary

# sklearn.neighbors.KNeighborsClassifier¶

In [391]:
neigh = KNeighborsClassifier(n_neighbors=7)
neigh.fit(X, y) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [392]:
# To predict popularity using test set's features
KNpredct_ary = neigh.predict(test_ary)

In [393]:
print(KNpredct_ary)

[0. 1. 0. ... 1. 0. 0.]


In [441]:
# Transfer the array of predicted popularity of test data into dataframe
KNpredct_df = pd.DataFrame(data=KNpredct_ary, columns=['popularity'])
KNpredct_df.head(10)

popularity
0         0.0
1         1.0
2         0.0
3         1.0
4         0.0
5         0.0
6         1.0
7         0.0
8         0.0
9         1.0

In [395]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(9, 'KNeigh', KNpredct_df['popularity'])

In [396]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     155       967        5        433       43         0   
1         0     342       869        5         13        0         1   
2         0     469      1515        0        762       18         0   
3         0      79       341        0        100        0         0   
4         0    1784      1468        0        416        6         0   

   crew_num  popularity  KNeigh  
0         0         0.0     0.0  
1         3         1.0     1.0  
2         0         0.0     0.0  
3         1         0.0     1.0  
4         3         1.0     0.0

# sklearn.naive_bayes.GaussianNB

In [397]:
gaus = GaussianNB()
gaus.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [398]:
# To predict popularity using test set's features
NBpredct_ary = gaus.predict(test_ary)

In [399]:
print(NBpredct_ary)

[0. 1. 0. ... 1. 0. 0.]


In [442]:
# Transfer the array of predicted popularity of test data into dataframe
NBpredct_df = pd.DataFrame(data=NBpredct_ary, columns=['popularity'])
NBpredct_df.head(10)

popularity
0         0.0
1         1.0
2         0.0
3         1.0
4         0.0
5         0.0
6         1.0
7         0.0
8         1.0
9         1.0

In [401]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(10, 'NBGaus', NBpredct_df['popularity'])

In [402]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     155       967        5        433       43         0   
1         0     342       869        5         13        0         1   
2         0     469      1515        0        762       18         0   
3         0      79       341        0        100        0         0   
4         0    1784      1468        0        416        6         0   

   crew_num  popularity  KNeigh  NBGaus  
0         0         0.0     0.0     0.0  
1         3         1.0     1.0     1.0  
2         0         0.0     0.0     0.0  
3         1         0.0     1.0     1.0  
4         3         1.0     0.0     0.0

In [403]:
# naive_bayes.GaussianNB classifier using partial fit (weight)
gaus_pf = GaussianNB()
gaus_pf.partial_fit(X, y, np.unique(y))

GaussianNB(priors=None, var_smoothing=1e-09)

In [404]:
# To predict popularity using test set's features, partial fit (weight)
NBpredct_pf_ary = gaus_pf.predict(test_ary)

In [405]:
print(NBpredct_pf_ary)

[0. 1. 0. ... 1. 0. 0.]


In [443]:
# Transfer the array of predicted popularity of test data into dataframe
NBpredct_pf_df = pd.DataFrame(data=NBpredct_ary, columns=['popularity'])
NBpredct_pf_df.head(10)

popularity
0         0.0
1         1.0
2         0.0
3         1.0
4         0.0
5         0.0
6         1.0
7         0.0
8         1.0
9         1.0

In [407]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(11, 'NBGaus_pf', NBpredct_pf_df['popularity'])

In [408]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     155       967        5        433       43         0   
1         0     342       869        5         13        0         1   
2         0     469      1515        0        762       18         0   
3         0      79       341        0        100        0         0   
4         0    1784      1468        0        416        6         0   

   crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  
0         0         0.0     0.0     0.0        0.0  
1         3         1.0     1.0     1.0        1.0  
2         0         0.0     0.0     0.0        0.0  
3         1         0.0     1.0     1.0        1.0  
4         3         1.0     0.0     0.0        0.0

# sklearn.svm.SVC

In [409]:
svc = SVC(gamma='auto')
svc.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [410]:
# To predict popularity using test set's features
SVCpredct_ary = svc.predict(test_ary)

In [411]:
print(SVCpredct_ary)

[0. 0. 0. ... 0. 0. 0.]


In [444]:
# Transfer the array of predicted popularity of test data into dataframe
SVCpredct_df = pd.DataFrame(data=SVCpredct_ary, columns=['popularity'])
SVCpredct_df.head(10)

popularity
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         0.0

# sklarn.neural_network.MLPClassifier

sklearn.model_selection.GridSearchCV

This method provided by sklearn helps identify suitable parameters passed in to certain classifiers.

In [413]:
mlp = MLPClassifier(hidden_layer_sizes=(100, ), solver='adam', max_iter=2000, n_iter_no_change=100)

In [414]:
mlp.fit(X, y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       n_iter_no_change=100, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [415]:
# To predict popularity using test set's features
MLPpredct_ary = mlp.predict(test_ary)
print(MLPpredct_ary)

[0. 1. 0. ... 1. 0. 0.]


In [445]:
# Transfer the array of predicted popularity of test data into dataframe
MLPpredct_df = pd.DataFrame(data=MLPpredct_ary, columns=['popularity'])
MLPpredct_df.head(10)

popularity
0         0.0
1         1.0
2         0.0
3         1.0
4         0.0
5         0.0
6         1.0
7         0.0
8         0.0
9         0.0

In [417]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(12, 'MLP', MLPpredct_df['popularity'])

In [418]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     155       967        5        433       43         0   
1         0     342       869        5         13        0         1   
2         0     469      1515        0        762       18         0   
3         0      79       341        0        100        0         0   
4         0    1784      1468        0        416        6         0   

   crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  MLP  
0         0         0.0     0.0     0.0        0.0  0.0  
1         3         1.0     1.0     1.0        1.0  1.0  
2         0         0.0     0.0     0.0        0.0  0.0  
3         1         0.0     1.0     1.0        1.0  1.0  
4         3         1.0     0.0     0.0        0.0  0.0

# sklearn.ensemble.VotingClassifier

Choose 3 classifiers: neigh, gaus, mlp

In [419]:
# 3 classifiers with hard voting
eclf1 = VotingClassifier(estimators=[('lr', neigh), ('rf', gaus), ('gnb', mlp)], voting='hard')
eclf1 = eclf1.fit(X, y)

In [420]:
# To predict popularity using test set's features
EHDpredct_ary = eclf1.predict(test_ary)
np.array_equal(eclf1.named_estimators_.lr.predict(X),eclf1.named_estimators_['lr'].predict(X))

True

In [421]:
print(EHDpredct_ary)

[0. 1. 0. ... 1. 0. 0.]


In [446]:
# Transfer the array of predicted popularity of test data into dataframe
EHDpredct_df = pd.DataFrame(data=EHDpredct_ary, columns=['popularity'])
EHDpredct_df.head(10)

popularity
0         0.0
1         1.0
2         0.0
3         1.0
4         0.0
5         0.0
6         1.0
7         0.0
8         0.0
9         1.0

In [423]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(13, 'EnsmblHD', EHDpredct_df['popularity'])

In [424]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     155       967        5        433       43         0   
1         0     342       869        5         13        0         1   
2         0     469      1515        0        762       18         0   
3         0      79       341        0        100        0         0   
4         0    1784      1468        0        416        6         0   

   crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  MLP  EnsmblHD  
0         0         0.0     0.0     0.0        0.0  0.0       0.0  
1         3         1.0     1.0     1.0        1.0  1.0       1.0  
2         0         0.0     0.0     0.0        0.0  0.0       0.0  
3         1         0.0     1.0     1.0        1.0  1.0       1.0  
4         3         1.0     0.0     0.0        0.0  0.0       0.0

Ensemble 3 classifiers with soft voting

In [425]:
eclf2 = VotingClassifier(estimators=[('lr', neigh), ('rf', gaus), ('gnb', mlp)], voting='soft')
eclf2 = eclf2.fit(X, y)

In [426]:
# To predict popularity using test set's features
ESFpredct_ary = eclf2.predict(test_ary)

In [427]:
print(ESFpredct_ary)

[0. 1. 0. ... 1. 0. 0.]


In [447]:
# Transfer the array of predicted popularity of test data into dataframe
ESFpredct_df = pd.DataFrame(data=ESFpredct_ary, columns=['popularity'])
ESFpredct_df.head(10)

popularity
0         0.0
1         1.0
2         0.0
3         1.0
4         0.0
5         0.0
6         1.0
7         0.0
8         0.0
9         1.0

In [429]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(14, 'EnsmblSF', ESFpredct_df['popularity'])

In [430]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     155       967        5        433       43         0   
1         0     342       869        5         13        0         1   
2         0     469      1515        0        762       18         0   
3         0      79       341        0        100        0         0   
4         0    1784      1468        0        416        6         0   

   crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  MLP  EnsmblHD  EnsmblSF  
0         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0  
1         3         1.0     1.0     1.0        1.0  1.0       1.0       1.0  
2         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0  
3         1         0.0     1.0     1.0        1.0  1.0       1.0       1.0  
4         3         1.0     0.0     0.0        0.0  0.0       0.0       0.0

Ensemble 3 classifiers with soft voting and weights

In [431]:
eclf3 = VotingClassifier(estimators=[('lr', neigh), ('rf', gaus), ('gnb', mlp)], voting='soft', weights=[2,1,1], 
                         flatten_transform=True)
eclf3 = eclf3.fit(X, y)

In [432]:
# To predict popularity using test set's features
ESWpredct_ary = eclf3.predict(test_ary)

print(eclf3.transform(X).shape)

(3194, 6)


In [433]:
print(ESWpredct_ary)

[0. 1. 0. ... 1. 0. 0.]


In [448]:
# Transfer the array of predicted popularity of test data into dataframe
ESWpredct_df = pd.DataFrame(data=ESWpredct_ary, columns=['popularity'])
ESWpredct_df.head(10)

popularity
0         0.0
1         1.0
2         0.0
3         1.0
4         0.0
5         0.0
6         1.0
7         0.0
8         0.0
9         1.0

In [435]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(15, 'EnsmblSW', ESWpredct_df['popularity'])

In [436]:
test_wtpopl.head(20)

language  cast_0  director  genre_0  company_0  country  cast_num  \
0          0     155       967        5        433       43         0   
1          0     342       869        5         13        0         1   
2          0     469      1515        0        762       18         0   
3          0      79       341        0        100        0         0   
4          0    1784      1468        0        416        6         0   
5          0     116      1921        8        396        0         0   
6          0     111        15        1         11        4         1   
7          0    1604      1857        5        983        0         0   
8          0     560      1040        8          5        0         0   
9          0     471       787        5        186        1         0   
10         0      31        42        1         31        0         0   
11         0     469       460       15         88        1         0   
12         0     366       262        6         55        0         1   
13         0     741      1983        8       1072       11         0   
14         0     865      1028        0        481        0         0   
15         0    1142      1370        8        675        1         0   
16         4    1826      2092       12       1143       12         0   
17         0      78        77        5          9        0         0   
18         0     734       338        8          2        0         0   
19         0     273        18        2          9        0         0   

    crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  MLP  EnsmblHD  EnsmblSF  \
0          0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
1          3         1.0     1.0     1.0        1.0  1.0       1.0       1.0   
2          0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
3          1         0.0     1.0     1.0        1.0  1.0       1.0       1.0   
4          3         1.0     0.0     0.0        0.0  0.0       0.0       0.0   
5          1         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
6          3         1.0     1.0     1.0        1.0  1.0       1.0       1.0   
7          0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
8          1         0.0     0.0     1.0        1.0  0.0       0.0       0.0   
9          1         0.0     1.0     1.0        1.0  0.0       1.0       1.0   
10         1         1.0     1.0     1.0        1.0  1.0       1.0       1.0   
11         3         1.0     0.0     1.0        1.0  1.0       1.0       1.0   
12         3         1.0     1.0     1.0        1.0  1.0       1.0       1.0   
13         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
14         1         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
15         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
16         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
17         2         1.0     1.0     1.0        1.0  1.0       1.0       1.0   
18         3         1.0     0.0     1.0        1.0  1.0       1.0       1.0   
19         0         0.0     1.0     1.0        1.0  1.0       1.0       1.0   

    EnsmblSW  
0        0.0  
1        1.0  
2        0.0  
3        1.0  
4        0.0  
5        0.0  
6        1.0  
7        0.0  
8        0.0  
9        1.0  
10       1.0  
11       1.0  
12       1.0  
13       0.0  
14       0.0  
15       0.0  
16       0.0  
17       1.0  
18       1.0  
19       1.0

# Evaluate Accuracy of Classifiers

In [437]:
lnth = len(test_wtpopl)
print(lnth)

1596


In [439]:
count1 = 0
count2 = 0
count3 = 0
count4 = 0
count5 = 0
count6 = 0
count7 = 0

for index, row in test_wtpopl.iterrows():
    popl = row['popularity']
    reslt1 = row["KNeigh"]
    reslt2 = row["NBGaus"]
    reslt3 = row["NBGaus_pf"]
    reslt4 = row["MLP"]
    reslt5 = row["EnsmblHD"]
    reslt6 = row["EnsmblSF"]
    reslt7 = row["EnsmblSW"]
    
    if popl==reslt1:
        count1 = count1 + 1
    if popl==reslt2:
        count2 = count2 + 1
    if popl==reslt3:
        count3 = count3 + 1
    if popl==reslt4:
        count4 = count4 + 1
    if popl==reslt5:
        count5 = count5 + 1
    if popl==reslt6:
        count6 = count6 + 1
    if popl==reslt7:
        count7 = count7 + 1
        
corctns1 = count1/lnth
corctns2 = count2/lnth
corctns3 = count3/lnth
corctns4 = count4/lnth
corctns5 = count5/lnth
corctns6 = count6/lnth
corctns7 = count7/lnth

print("KNeighboyhood: ", corctns1)
print("Naive_bayes.GaussianNB: ", corctns2)
print("Naive_bayes.GaussianNB (partial fit): ", corctns3)
print("MLPClassifier: ", corctns4)
print("Ensemble HD Voting: ", corctns5)
print("Ensemble SF Voting: ", corctns6)
print("Ensemble Pro: ", corctns7)

KNeighboyhood:  0.7255639097744361
Naive_bayes.GaussianNB:  0.7593984962406015
Naive_bayes.GaussianNB (partial fit):  0.7593984962406015
MLPClassifier:  0.7706766917293233
Ensemble HD Voting:  0.7650375939849624
Ensemble SF Voting:  0.7731829573934837
Ensemble Pro:  0.7738095238095238


In [440]:
# Export the result of certain round classification as backup, specify the version
test_wtpopl.to_csv('chp5_classifiers/version_X/result_vrsX.csv', index=False) # change to result_vrsX.csv