# Chapter 5 Classifiers

# Import Training&Test Data after Data Preprocessing

All csv files imported here shall be shuffled, thus shall be the same with shuffled one displayed in Data Preprocessing (in datasplit_train_test.ipynb file). Data shall be the same version with backup stored in file chp5_classifiers.

In [156]:
import pandas as pd
import numpy as np

In [157]:
# Read in csv file of training and testing record
train_df = pd.read_csv("./chp5_classifiers/train_set.csv")
test_df = pd.read_csv("./chp5_classifiers/test_set.csv") 

test_wtpopl = pd.read_csv("./chp5_classifiers/test_wtpopl.csv") 

In [158]:
# Display first 5 rows of training dataframe, check whether the same with shuffled one displayed in Data Preprocessing file
train_df.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         3     513      1254        3        193       15         0   
1         0     950      1145        5        542        3         1   
2         0      84       186        8         31        0         0   
3         0     176        85       12          1        1         3   
4         0    1125      1383        5        685       13         0   

   crew_num  popularity  
0         0         0.0  
1         2         0.0  
2         3         1.0  
3         3         1.0  
4         0         0.0

In [159]:
# Extract label class popularity from training set
labl_df = train_df['popularity']
labl_df.head()

0    0.0
1    0.0
2    1.0
3    1.0
4    0.0
Name: popularity, dtype: float64

In [160]:
# Remove label class from training set
train_set = train_df.drop(columns=['popularity'])
train_set.head()

language  cast_0  director  genre_0  company_0  country  cast_num  crew_num
0         3     513      1254        3        193       15         0         0
1         0     950      1145        5        542        3         1         2
2         0      84       186        8         31        0         0         3
3         0     176        85       12          1        1         3         3
4         0    1125      1383        5        685       13         0         0

In [161]:
# Display first 5 rows of test dataframe, check whether the same with shuffled one displayed before
test_df.head()

language  cast_0  director  genre_0  company_0  country  cast_num  crew_num
0         0     809      2053        5       1116        0         0         1
1         0     252       823        5         78        0         1         1
2         0    1172      2000       15        697        6         0         1
3         4    1745      2011        8       1088       20         0         0
4         0     357       423        5          9        0         0         3

In [162]:
# Transfer type of ddtaframe to numpy array for training and test sets and label set
train_ary = np.array(train_set)
print(train_ary[0:5])
test_ary = np.array(test_df)
print(test_ary[0:5])
labl_ary = np.array(labl_df)
print(labl_ary[0:5])

[[   3  513 1254    3  193   15    0    0]
 [   0  950 1145    5  542    3    1    2]
 [   0   84  186    8   31    0    0    3]
 [   0  176   85   12    1    1    3    3]
 [   0 1125 1383    5  685   13    0    0]]
[[   0  809 2053    5 1116    0    0    1]
 [   0  252  823    5   78    0    1    1]
 [   0 1172 2000   15  697    6    0    1]
 [   4 1745 2011    8 1088   20    0    0]
 [   0  357  423    5    9    0    0    3]]
[0. 0. 1. 1. 0.]


# Classification

So far, all data array required shall be organized in suitable format and correctly imported.

Training Features: train_ary

Training Labels: labl_ary

Testing Features: test_ary

In [163]:
from sklearn.neighbors import KNeighborsClassifier

In [164]:
from sklearn.naive_bayes import GaussianNB

In [165]:
from sklearn.svm import SVC

In [166]:
from sklearn.neural_network import MLPClassifier

In [167]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [168]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [169]:
# Array of movies consists of features selected as input
X = train_ary

In [170]:
# Popularity label of sample data 0-unpopular 1-popular
y = labl_ary

# sklearn.neighbors.KNeighborsClassifier¶

In [171]:
neigh = KNeighborsClassifier(n_neighbors=7)
neigh.fit(X, y) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [172]:
# To predict popularity using test set's features
KNpredct_ary = neigh.predict(test_ary)

In [173]:
print(KNpredct_ary)

[0. 0. 0. ... 0. 0. 0.]


In [174]:
# Transfer the array of predicted popularity of test data into dataframe
KNpredct_df = pd.DataFrame(data=KNpredct_ary, columns=['popularity'])
KNpredct_df.head(50)

popularity
0          0.0
1          0.0
2          0.0
3          0.0
4          1.0
5          0.0
6          0.0
7          0.0
8          0.0
9          0.0
10         0.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         1.0
17         0.0
18         0.0
19         0.0
20         0.0
21         0.0
22         0.0
23         0.0
24         0.0
25         0.0
26         0.0
27         0.0
28         0.0
29         0.0
30         0.0
31         0.0
32         0.0
33         0.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         0.0
40         0.0
41         0.0
42         1.0
43         0.0
44         0.0
45         0.0
46         0.0
47         0.0
48         0.0
49         0.0

In [175]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(9, 'KNeigh', KNpredct_df['popularity'])

In [176]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     809      2053        5       1116        0         0   
1         0     252       823        5         78        0         1   
2         0    1172      2000       15        697        6         0   
3         4    1745      2011        8       1088       20         0   
4         0     357       423        5          9        0         0   

   crew_num  popularity  KNeigh  
0         1         0.0     0.0  
1         1         1.0     0.0  
2         1         0.0     0.0  
3         0         0.0     0.0  
4         3         1.0     1.0

# sklearn.naive_bayes.GaussianNB

In [177]:
gaus = GaussianNB()
gaus.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [178]:
# To predict popularity using test set's features
NBpredct_ary = gaus.predict(test_ary)

In [179]:
print(NBpredct_ary)

[0. 1. 0. ... 0. 0. 0.]


In [180]:
# Transfer the array of predicted popularity of test data into dataframe
NBpredct_df = pd.DataFrame(data=NBpredct_ary, columns=['popularity'])
NBpredct_df.head(50)

popularity
0          0.0
1          1.0
2          0.0
3          0.0
4          1.0
5          0.0
6          1.0
7          0.0
8          0.0
9          0.0
10         0.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         1.0
17         0.0
18         0.0
19         0.0
20         0.0
21         0.0
22         0.0
23         0.0
24         0.0
25         0.0
26         1.0
27         0.0
28         0.0
29         0.0
30         0.0
31         0.0
32         0.0
33         0.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         0.0
40         0.0
41         0.0
42         0.0
43         0.0
44         0.0
45         0.0
46         0.0
47         0.0
48         0.0
49         0.0

In [181]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(10, 'NBGaus', NBpredct_df['popularity'])

In [182]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     809      2053        5       1116        0         0   
1         0     252       823        5         78        0         1   
2         0    1172      2000       15        697        6         0   
3         4    1745      2011        8       1088       20         0   
4         0     357       423        5          9        0         0   

   crew_num  popularity  KNeigh  NBGaus  
0         1         0.0     0.0     0.0  
1         1         1.0     0.0     1.0  
2         1         0.0     0.0     0.0  
3         0         0.0     0.0     0.0  
4         3         1.0     1.0     1.0

In [183]:
# naive_bayes.GaussianNB classifier using partial fit (weight)
gaus_pf = GaussianNB()
gaus_pf.partial_fit(X, y, np.unique(y))

GaussianNB(priors=None, var_smoothing=1e-09)

In [184]:
# To predict popularity using test set's features, partial fit (weight)
NBpredct_pf_ary = gaus_pf.predict(test_ary)

In [185]:
print(NBpredct_pf_ary)

[0. 1. 0. ... 0. 0. 0.]


In [186]:
# Transfer the array of predicted popularity of test data into dataframe
NBpredct_pf_df = pd.DataFrame(data=NBpredct_ary, columns=['popularity'])
NBpredct_pf_df.head(50)

popularity
0          0.0
1          1.0
2          0.0
3          0.0
4          1.0
5          0.0
6          1.0
7          0.0
8          0.0
9          0.0
10         0.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         1.0
17         0.0
18         0.0
19         0.0
20         0.0
21         0.0
22         0.0
23         0.0
24         0.0
25         0.0
26         1.0
27         0.0
28         0.0
29         0.0
30         0.0
31         0.0
32         0.0
33         0.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         0.0
40         0.0
41         0.0
42         0.0
43         0.0
44         0.0
45         0.0
46         0.0
47         0.0
48         0.0
49         0.0

In [187]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(11, 'NBGaus_pf', NBpredct_pf_df['popularity'])

In [188]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     809      2053        5       1116        0         0   
1         0     252       823        5         78        0         1   
2         0    1172      2000       15        697        6         0   
3         4    1745      2011        8       1088       20         0   
4         0     357       423        5          9        0         0   

   crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  
0         1         0.0     0.0     0.0        0.0  
1         1         1.0     0.0     1.0        1.0  
2         1         0.0     0.0     0.0        0.0  
3         0         0.0     0.0     0.0        0.0  
4         3         1.0     1.0     1.0        1.0

# sklearn.svm.SVC

In [189]:
svc = SVC(gamma='auto')
svc.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [190]:
# To predict popularity using test set's features
SVCpredct_ary = svc.predict(test_ary)

In [191]:
print(SVCpredct_ary)

[1. 1. 1. ... 1. 1. 1.]


In [193]:
# Transfer the array of predicted popularity of test data into dataframe
SVCpredct_df = pd.DataFrame(data=SVCpredct_ary, columns=['popularity'])
SVCpredct_df.head(50)

popularity
0          1.0
1          1.0
2          1.0
3          1.0
4          1.0
5          1.0
6          1.0
7          1.0
8          1.0
9          1.0
10         1.0
11         1.0
12         1.0
13         1.0
14         1.0
15         1.0
16         1.0
17         1.0
18         1.0
19         1.0
20         1.0
21         1.0
22         1.0
23         1.0
24         1.0
25         1.0
26         1.0
27         1.0
28         1.0
29         1.0
30         1.0
31         1.0
32         1.0
33         1.0
34         1.0
35         1.0
36         1.0
37         1.0
38         1.0
39         1.0
40         1.0
41         1.0
42         1.0
43         1.0
44         1.0
45         1.0
46         1.0
47         1.0
48         1.0
49         1.0

# sklarn.neural_network.MLPClassifier

sklearn.model_selection.GridSearchCV

This method provided by sklearn helps identify suitable parameters passed in to certain classifiers.

In [194]:
mlp = MLPClassifier(hidden_layer_sizes=(100, ), solver='adam', max_iter=2000, n_iter_no_change=100)

In [195]:
mlp.fit(X, y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       n_iter_no_change=100, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [196]:
# To predict popularity using test set's features
MLPpredct_ary = mlp.predict(test_ary)
print(MLPpredct_ary)

[1. 1. 0. ... 1. 1. 1.]


In [198]:
# Transfer the array of predicted popularity of test data into dataframe
MLPpredct_df = pd.DataFrame(data=MLPpredct_ary, columns=['popularity'])
MLPpredct_df.head(50)

popularity
0          1.0
1          1.0
2          0.0
3          0.0
4          1.0
5          1.0
6          1.0
7          1.0
8          1.0
9          0.0
10         1.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         1.0
17         0.0
18         1.0
19         0.0
20         0.0
21         0.0
22         0.0
23         1.0
24         0.0
25         1.0
26         1.0
27         1.0
28         1.0
29         0.0
30         0.0
31         1.0
32         0.0
33         0.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         0.0
40         0.0
41         0.0
42         1.0
43         0.0
44         0.0
45         0.0
46         0.0
47         1.0
48         0.0
49         1.0

In [199]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(12, 'MLP', MLPpredct_df['popularity'])

In [200]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     809      2053        5       1116        0         0   
1         0     252       823        5         78        0         1   
2         0    1172      2000       15        697        6         0   
3         4    1745      2011        8       1088       20         0   
4         0     357       423        5          9        0         0   

   crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  MLP  
0         1         0.0     0.0     0.0        0.0  1.0  
1         1         1.0     0.0     1.0        1.0  1.0  
2         1         0.0     0.0     0.0        0.0  0.0  
3         0         0.0     0.0     0.0        0.0  0.0  
4         3         1.0     1.0     1.0        1.0  1.0

# sklearn.ensemble.VotingClassifier

Choose 3 classifiers: neigh, gaus, mlp

In [201]:
# 3 classifiers with hard voting
eclf1 = VotingClassifier(estimators=[('lr', neigh), ('rf', gaus), ('gnb', mlp)], voting='hard')
eclf1 = eclf1.fit(X, y)

In [204]:
# To predict popularity using test set's features
EHDpredct_ary = eclf1.predict(test_ary)
np.array_equal(eclf1.named_estimators_.lr.predict(X),eclf1.named_estimators_['lr'].predict(X))

True

In [205]:
print(EHDpredct_ary)

[0. 1. 0. ... 0. 0. 0.]


In [206]:
# Transfer the array of predicted popularity of test data into dataframe
EHDpredct_df = pd.DataFrame(data=EHDpredct_ary, columns=['popularity'])
EHDpredct_df.head(50)

popularity
0          0.0
1          1.0
2          0.0
3          0.0
4          1.0
5          0.0
6          0.0
7          0.0
8          0.0
9          0.0
10         0.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         1.0
17         0.0
18         0.0
19         0.0
20         0.0
21         0.0
22         0.0
23         0.0
24         0.0
25         0.0
26         0.0
27         0.0
28         0.0
29         0.0
30         0.0
31         0.0
32         0.0
33         0.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         0.0
40         0.0
41         0.0
42         0.0
43         0.0
44         0.0
45         0.0
46         0.0
47         0.0
48         0.0
49         0.0

In [207]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(13, 'EnsmblHD', EHDpredct_df['popularity'])

In [209]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     809      2053        5       1116        0         0   
1         0     252       823        5         78        0         1   
2         0    1172      2000       15        697        6         0   
3         4    1745      2011        8       1088       20         0   
4         0     357       423        5          9        0         0   

   crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  MLP  EnsmblHD  
0         1         0.0     0.0     0.0        0.0  1.0       0.0  
1         1         1.0     0.0     1.0        1.0  1.0       1.0  
2         1         0.0     0.0     0.0        0.0  0.0       0.0  
3         0         0.0     0.0     0.0        0.0  0.0       0.0  
4         3         1.0     1.0     1.0        1.0  1.0       1.0

Ensemble 3 classifiers with soft voting

In [210]:
eclf2 = VotingClassifier(estimators=[('lr', neigh), ('rf', gaus), ('gnb', mlp)], voting='soft')
eclf2 = eclf2.fit(X, y)

In [211]:
# To predict popularity using test set's features
ESFpredct_ary = eclf2.predict(test_ary)

In [212]:
print(ESFpredct_ary)

[0. 1. 0. ... 0. 0. 0.]


In [213]:
# Transfer the array of predicted popularity of test data into dataframe
ESFpredct_df = pd.DataFrame(data=ESFpredct_ary, columns=['popularity'])
ESFpredct_df.head(50)

popularity
0          0.0
1          1.0
2          0.0
3          0.0
4          1.0
5          0.0
6          1.0
7          0.0
8          0.0
9          0.0
10         0.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         1.0
17         0.0
18         0.0
19         0.0
20         0.0
21         0.0
22         0.0
23         0.0
24         0.0
25         0.0
26         1.0
27         0.0
28         0.0
29         0.0
30         0.0
31         0.0
32         0.0
33         0.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         0.0
40         0.0
41         0.0
42         0.0
43         0.0
44         0.0
45         0.0
46         0.0
47         0.0
48         0.0
49         0.0

In [214]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(14, 'EnsmblSF', ESFpredct_df['popularity'])

In [215]:
test_wtpopl.head()

language  cast_0  director  genre_0  company_0  country  cast_num  \
0         0     809      2053        5       1116        0         0   
1         0     252       823        5         78        0         1   
2         0    1172      2000       15        697        6         0   
3         4    1745      2011        8       1088       20         0   
4         0     357       423        5          9        0         0   

   crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  MLP  EnsmblHD  EnsmblSF  
0         1         0.0     0.0     0.0        0.0  1.0       0.0       0.0  
1         1         1.0     0.0     1.0        1.0  1.0       1.0       1.0  
2         1         0.0     0.0     0.0        0.0  0.0       0.0       0.0  
3         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0  
4         3         1.0     1.0     1.0        1.0  1.0       1.0       1.0

Ensemble 3 classifiers with soft voting and weights

In [216]:
eclf3 = VotingClassifier(estimators=[('lr', neigh), ('rf', gaus), ('gnb', mlp)], voting='soft', weights=[2,1,1], 
                         flatten_transform=True)
eclf3 = eclf3.fit(X, y)

In [219]:
# To predict popularity using test set's features
ESWpredct_ary = eclf3.predict(test_ary)

print(eclf3.transform(X).shape)

(3194, 6)


In [220]:
print(ESWpredct_ary)

[0. 1. 0. ... 0. 0. 0.]


In [221]:
# Transfer the array of predicted popularity of test data into dataframe
ESWpredct_df = pd.DataFrame(data=ESWpredct_ary, columns=['popularity'])
ESWpredct_df.head(50)

popularity
0          0.0
1          1.0
2          0.0
3          0.0
4          1.0
5          0.0
6          1.0
7          0.0
8          0.0
9          0.0
10         0.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         1.0
17         0.0
18         0.0
19         0.0
20         0.0
21         0.0
22         0.0
23         0.0
24         0.0
25         0.0
26         1.0
27         0.0
28         0.0
29         0.0
30         0.0
31         0.0
32         0.0
33         0.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         0.0
40         0.0
41         0.0
42         0.0
43         0.0
44         0.0
45         0.0
46         0.0
47         0.0
48         0.0
49         0.0

In [222]:
# Insert result into test_wtpopl, check the prediction correctness
test_wtpopl.insert(15, 'EnsmblSW', ESWpredct_df['popularity'])

In [225]:
test_wtpopl.head(20)

language  cast_0  director  genre_0  company_0  country  cast_num  \
0          0     809      2053        5       1116        0         0   
1          0     252       823        5         78        0         1   
2          0    1172      2000       15        697        6         0   
3          4    1745      2011        8       1088       20         0   
4          0     357       423        5          9        0         0   
5          0     460      1432        8        193       15         0   
6          0    1373      1765       11          9        0         3   
7          0     873      1528        9         18        0         0   
8          0    1694      1961        8       1055        0         0   
9          0    1462      1724        8        906        0         0   
10         0    1496      1760        5        921        0         1   
11         0    1595      1850        5        422       20         0   
12         0     484      1698        8        501        7         0   
13         0    1742       147        5         63        0         0   
14         0    1676      1941       15       1042        0         0   
15         0    1931      2188       19        193       15         0   
16         0     602       322        5        186        1         1   
17         0    1399      1668       17         18        0         0   
18         0     688      1777       12        930        4         0   
19         0    1533      1167        5        636        0         0   

    crew_num  popularity  KNeigh  NBGaus  NBGaus_pf  MLP  EnsmblHD  EnsmblSF  \
0          1         0.0     0.0     0.0        0.0  1.0       0.0       0.0   
1          1         1.0     0.0     1.0        1.0  1.0       1.0       1.0   
2          1         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
3          0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
4          3         1.0     1.0     1.0        1.0  1.0       1.0       1.0   
5          0         0.0     0.0     0.0        0.0  1.0       0.0       0.0   
6          2         0.0     0.0     1.0        1.0  1.0       0.0       1.0   
7          3         1.0     0.0     0.0        0.0  1.0       0.0       0.0   
8          3         0.0     0.0     0.0        0.0  1.0       0.0       0.0   
9          0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
10         2         0.0     0.0     0.0        0.0  1.0       0.0       0.0   
11         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
12         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
13         1         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
14         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
15         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
16         1         1.0     1.0     1.0        1.0  1.0       1.0       1.0   
17         0         0.0     0.0     0.0        0.0  0.0       0.0       0.0   
18         3         1.0     0.0     0.0        0.0  1.0       0.0       0.0   
19         2         0.0     0.0     0.0        0.0  0.0       0.0       0.0   

    EnsmblSW  
0        0.0  
1        1.0  
2        0.0  
3        0.0  
4        1.0  
5        0.0  
6        1.0  
7        0.0  
8        0.0  
9        0.0  
10       0.0  
11       0.0  
12       0.0  
13       0.0  
14       0.0  
15       0.0  
16       1.0  
17       0.0  
18       0.0  
19       0.0

In [227]:
# Export the result of certain round classification as backup, specify the version
test_wtpopl.to_csv('chp5_classifiers/version_0/result_vrs0.csv', index=False) # change to result_vrsX.csv